## Data 118, Fall 2022, University of Chicago
# Homework 1: Strings, Expressions and Arrays (50 points)

Please complete this notebook by filling in the cells provided. The solved homework should be uploaded to Canvas.   Please do not put your answers in more than one file unless you want the TAs to miss some of your answers.

#### Reading:
- Data8 Textbook chapters  [3.1-3.3](http://www.inferentialthinking.com/chapters/03/programming-in-python.html) (Programming in Python),
[4](https://www.inferentialthinking.com/chapters/04/Data_Types) (Data Types) and [5](https://www.inferentialthinking.com/chapters/05/Sequences.html) (Sequences).

#### Deadline:

This assignment is due on **Friday, October 7 at 9:00am**. Late work will not be accepted unless you have made special arrangements with the instructors.

Directly sharing answers is not okay, but discussing problems with the course staff is encouraged, and with other students is allowed. 

You should start early so that you have time to get help if you're stuck. 

In [97]:
# Don't change this cell; just run it. 

import numpy as np
import pandas as pd

import warnings
warnings.simplefilter('ignore', FutureWarning)

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## 1. Strings (9 points)

Run the following cell. Before running try to guess the answer. Explain why the output of that command is the integer you obtain.

In [3]:
len('U of C')

6

**Question 1.**  Explain why the above cell gives the answer it does.


**It is returning the length of the text between the apostrophes including the spaces That would be 6 characters.**

Here is a short paragraph from Rachel Carson's book Silent Spring, which first appeared in the New Yorker in 1962.
Note that the string 'spring' contains newline characters, which we would like to get rid of.

In [29]:
spring = '''THE HISTORY OF LIFE on earth has been a history of
interaction between living things and their 
surroundings. To a large extent, the physical form and 
the habits of the earth's vegetation and its animal life
have been molded by the environment. Considering 
the whole span of earthly time, the opposite effect, in 
which life actually modifies its surroundings, has been 
relatively slight. Only within the moment of time 
represented by the present century has one species—
man—acquired significant power to alter the nature of 
his world.'''

**Question 2.** Using `str.replace()`, create a string called `stanza_oneline` with all the newlines replaced by spaces. An example of using `str.replace()` is in the first cell code of Question 4.

In [33]:
#Q2 Answer 
stanza_oneline = spring.replace('\n',' ')
stanza_oneline

"THE HISTORY OF LIFE on earth has been a history of interaction between living things and their  surroundings. To a large extent, the physical form and  the habits of the earth's vegetation and its animal life have been molded by the environment. Considering  the whole span of earthly time, the opposite effect, in  which life actually modifies its surroundings, has been  relatively slight. Only within the moment of time  represented by the present century has one species— man—acquired significant power to alter the nature of  his world."

**Question 3.**  Write python expressions that count the number of words and the number of sentences in this paragraph.  (**Hint**:  Check your answer. If your expression gives the wrong answer, fix your expression.) 

In [36]:
#Q3 Answer part 1
fix1 = stanza_oneline.replace('—',' ')
fix2 = fix1.replace('  ',' ')
number_words = np.char.count(fix2,' ') + 1
number_words

88

In [17]:
#Q3 Answer part 2
number_sentences = np.char.count(spring, '.')
number_sentences

array(4)

**Question 4.** Use the *replace* function for strings to change the string *'machine learning'* into the string *'learning machine'*. You must do everything into one line of code and you can only replace one full word with a different full word. An example of using *replace* twice in one line of code is below. [Note: the output should be a string of the same length as the one you started with; no extra spaces etc.] 

In [38]:
# this cell illustrates the use of .replace
'on campus'.replace('on','happy').replace('campus','place')

'happy place'

In [40]:
#Q4 answer here
'machine learning'.replace('machine','learning').replace(' learning',' machine')

'learning machine'

The *split* command breaks a string into a list a strings by a specified separator. Also recall that numbers in square braces access elements in a list "slicing" by number.  Below is an example of using the `split()` command, list slicing, and the string concatenation using + to execute the following: from the string *'learning is done by machine'* obtain the string '*machine learning'*.

In [41]:
mystring = "learning is done by machine"
mynewstring = mystring.split()[4] + " " + mystring.split()[0]
mynewstring

'machine learning'

In [42]:
mystring1 = 'Why do we have to do this? Is this going to be on the test?'


**Question 5.**  The string `mystring1` is introduced in the cell above. Build the string "we have to do this" from the parts of `mystring1.split()`, and remove the question marks as needed.  


In [50]:
# Q5 answer here
split1 = mystring1.split()
answer5 = split1[2] + " " + split1[3] + " " + split1[4] + " " + split1[5] + " " + split1[8]
answer5

'we have to do this'

## 2. Names and Assignment Statements (9 points)

Python sometimes gives you difficult-to-get-used-to error messages. 

In [56]:
# assign four new variables with unsurprising values
one, two, three, four = 1,2,3,4

**Question 6.** 
What happens when we run this expression?  (You may want to check the python documentation under the heading "Operator precedence" https://docs.python.org/3/reference/expressions.html#operator-precedence for the order-of-operations hierarchy in python.)

In [57]:
result = 4 + two == 6

Choose the best explanation of what this cell does and put your answer (a, b, c, or d) in the cell below.

&emsp;a. Add 4 and two, store the result in 'result' and compare this to the value 6

&emsp;b. Compare two and 6 (False), add 4, and store the sum in 'result'

&emsp;c. Add 4 and two, compare to 6, and store the comparison in 'result'

&emsp;d. Generates an error because 'result' is not defined.

Answer to Q6 is: c

**Question 7.**  

In [58]:
four = two plus two

SyntaxError: invalid syntax (3432669223.py, line 1)

Choose the best explanation of what this cell does and put your answer (a, b, c, or d) in the cell below.

&emsp;a. The `plus` operation only applies to numbers, not the word "two".

&emsp;b. `plus` is not defined.

&emsp;c. "=" is the assignment operator, not the test-for-equality operator, which is "==".

&emsp;d. `plus` is not a binary operator.

Answer to Q7 is: d

**Question 8.** Choose the best explanation of what's wrong with the code in the cell below and put your answer (a, b, c, or d) in the cell below that.

&emsp;a. The + operation only applies to numbers, not the word `six`.

&emsp;b. `six` is not defined.

&emsp;c. "=" is the assignment operator, not the test-for-equality operator, which is "==".

&emsp;d. `+` is not a binary operator.

In [60]:
number = 2 + six 

NameError: name 'six' is not defined

Answer to Q8 is: b

<img width=150 src=https://upload.wikimedia.org/wikipedia/commons/1/13/Partially-reflected-plutonium-sphere.jpeg>

**Question 9. Doing polynomial math.** A certain device was made by casting and machining 6.46 kg of plutonium alloy into the shape of a sphere.  The alloy has a density of 15.6 g / cm$^3$, and the volume of a sphere is $V = 4 \pi r^2 / 3$.  What is the diameter of the sphere if the sphere is solid? 

**Hint:** use algebra to find `r` as a function of `V`, then implement your expression in python.

**Hint:** The `**` operator takes a number to a power. See the examples in the cell below.

**Hint:** A photograph of the sphere is above with a ruler in inches nearby; image is at https://upload.wikimedia.org/wikipedia/commons/1/13/Partially-reflected-plutonium-sphere.jpeg 

In [92]:
print("The square root of 81 is", 81 **(0.5) )
print("The fourth root of 81 is", 81 **(0.25) )

The square root of 81 is 9.0
The fourth root of 81 is 3.0
The third root of 27 is  3.0


In [131]:
#Q9 Answer code
diameter = 2*((3*6.46/(4*15600*np.pi))**(1/3))# wrong if does not include correct units!
print(str(diameter) + ' m')

0.09247757490131363 m


## 3. Creating Arrays (15 points)

**Question 10.** Make a python list or tuple containing the names of the Laurentian Great Lakes: Ontario, Erie, Huron, Michigan, and Superior.

In [69]:
# Q10 Answer code
Greatlakes = ["Ontario","Erie","Huron","Michigan","Superior"]

**Question 11.** Build the string "Ontario, Erie, Huron, Michigan, and Superior" from the above list or tuple and other ingredients you have in your kitchen.

**Advanced Hint**:Strings have a method called `join`.  `join` takes one argument, a list or tuple of strings.  It returns a single string.  Specifically, the value of `a_string.join(a_list)` is a single string that's the [concatenation](https://en.wikipedia.org/wiki/Concatenation) ("putting together") of all the strings in `a_list`, with the string `a_string` inserted in between each of the strings.


In [76]:
# Q11 Answer code
Greatstring = ', '.join(Greatlakes)
Greatstring = Greatstring.replace("Superior","and Superior")
Greatstring

'Ontario, Erie, Huron, Michigan, and Superior'

## 4.  Arrays Indexing and Arithmetic (9 points)

These exercises give you practice accessing individual elements of arrays.  In Python (and in many programming languages), elements are accessed by *index*, so the first element is the element at index 0.  

**Question 12.** The cell below creates an array of some numbers.  Set `third_element` to the third element of `some_numbers`.

In [77]:
#Q12 Answer code
some_numbers = np.array([1,1,2,3,5,8,13,21])

third_element = some_numbers[2]
third_element

2

**Question 13.** Multiply the numbers 243, 569, 577, 577, and 600 by 0.3048.  For this question, **don't** use arrays.

In [79]:
#Q13 Answer code 
first_product = 243*0.3048
second_product = 569*0.3048
third_product = 577*0.3048
fourth_product = 577*0.3048
fifth_product = 600*0.3048

print(first_product, second_product, third_product, fourth_product, fifth_product)

74.0664 173.43120000000002 175.86960000000002 175.86960000000002 182.88


**Question 14.** Now, do the same calculation, but using an array called `elevations_ft` (that will contain the numbers above) and only a single multiplication (`*`) operator.  Store the 4 results in an array named `elevations_m`.  **Hint:**  you should use `np.array()` 

In [95]:
#Q14 answer code
elevations_ft = np.array([243,569,577,577,600])
elevations_m = elevations_ft*0.3048

[243 569 577 577 600]


array([ 74.0664, 173.4312, 175.8696, 175.8696, 182.88  ])

## 5. Lake level diffs (8 points)

The cell below loads monthly measurements of the level of Lake Michigan above sea level (in feet) for a ten-year period.

The next cell loads the data into a pandas dataframe.

In [121]:
# read the data into a pandas dataframe
# make sure you specify the correct path to your data file
lake = pd.read_csv(r"C:\Users\ja123\Downloads\LAKELEVEL_30years.csv")[['Date', 'MSL (ft)']]

# this shows the first 4 rows of the table
lake.head(4)

Date  MSL (ft)
0  1992/01/01   578.671
1  1992/02/01   578.727
2  1992/03/01   578.920
3  1992/04/01   579.041

In the next cell, the name `population` is assigned to an **array** of population estimates.

In [122]:
# And this cell puts the numbers in a numpy array called `lakelevel`.
lakelevel = lake["MSL (ft)"].values
lakelevel

array([578.671, 578.727, 578.92 , 579.041, 579.304, 579.285, 579.319,
       579.237, 579.077, 579.026, 579.274, 579.088, 579.298, 579.275,
       579.259, 579.705, 579.833, 580.177, 580.394, 580.328, 580.108,
       579.82 , 579.678, 579.491, 579.4  , 579.383, 579.436, 579.57 ,
       579.78 , 579.915, 580.118, 580.095, 579.977, 579.688, 579.455,
       579.367, 579.183, 579.072, 579.088, 579.219, 579.462, 579.675,
       579.469, 579.606, 579.314, 578.825, 578.865, 578.734, 578.72 ,
       578.779, 578.926, 579.112, 579.53 , 580.066, 580.236, 580.252,
       580.302, 580.053, 579.962, 579.968, 579.994, 580.168, 580.426,
       580.576, 581.02 , 581.242, 581.415, 581.385, 581.214, 580.759,
       580.386, 580.055, 579.962, 580.01 , 580.111, 580.555, 580.586,
       580.44 , 580.37 , 580.09 , 579.667, 579.274, 578.776, 578.444,
       578.407, 578.369, 578.365, 578.556, 578.491, 578.635, 578.696,
       578.733, 578.288, 577.886, 577.52 , 577.297, 577.216, 577.079,
       577.252, 577.

In the following questions, you will apply some built-in Numpy functions to this array.

The difference function `np.diff` subtracts each element in an array by the element that preceeds it. As a result, the length of the array `np.diff` returns will always be one less than the length of the input array.

The cumulative sum function `np.cumsum` outputs an array of partial sums. For example, the third element in the output array corresponds to the sum of the first, second, and third elements.

In [126]:
#example of np.diff
temp_array = np.array([0,1,1,2,3,5,8])
np.diff(temp_array)

array([1, 0, 1, 1, 2, 3])

In [124]:
#example of cumsum
np.cumsum(temp_array)

array([ 0,  1,  2,  4,  7, 12, 20], dtype=int32)

**Question 15.** Often we are interested understanding how values change with time. Use `np.diff` and `np.max` (or just `max`) to calculate the largest  change in lake level between two consecutive months.

In [128]:
# Q15 answer code
max(np.diff(lakelevel))

0.7229999999999563

**Question 16.** Describe in words the result of the following expression. What do the values in the resulting array represent? 

In [ ]:
np.cumsum(np.diff(lakelevel))

*Q16 Answer here:* The cumulative change in the lakelevel of Lake Michigan over the 10 year period. 

**Question 17**  These two expressions give different answers.  Why is that?

In [129]:
len(np.cumsum(np.diff(lakelevel))), len(lakelevel)

(358, 359)

*Q17 Answer here:* Because the np.diff function returns an array of length 1 less. It takes the difference between two values, and there are arraylength-1 differences. 